In [64]:
from tensorflow.keras.preprocessing.text import one_hot

In [65]:
##sent
sent=[
    'the glass of the milk',
    'the glass of the juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [66]:
sent

['the glass of the milk',
 'the glass of the juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [67]:
#define the vocabulary size
vocab_size=10000

In [68]:
#one hot representation
onehot_repr=[one_hot(words,vocab_size) for words in sent]
onehot_repr

[[3005, 7648, 3295, 3005, 6585],
 [3005, 7648, 3295, 3005, 7728],
 [3005, 5987, 3295, 5150],
 [7294, 2597, 4775, 2277, 3101],
 [7294, 2597, 4775, 2277, 7646],
 [6636, 3005, 3024, 3295, 1138],
 [4306, 3028, 2036, 2277]]

In [69]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 3005 7648 3295 3005 6585]
 [   0    0    0 3005 7648 3295 3005 7728]
 [   0    0    0    0 3005 5987 3295 5150]
 [   0    0    0 7294 2597 4775 2277 3101]
 [   0    0    0 7294 2597 4775 2277 7646]
 [   0    0    0 6636 3005 3024 3295 1138]
 [   0    0    0    0 4306 3028 2036 2277]]


In [70]:
#feature representation
dim=10
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [71]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.04139786, -0.02385365, -0.04399638, -0.03862389,
          0.04960659, -0.04309141, -0.02511778, -0.02147905,
          0.04910827,  0.01750758],
        [-0.02780038,  0.02473172, -0.00084607,  0.00022495,
          0.02255764, -0.03845737,  0.01712784,  0.03489533,
         -0.03803753, -0.03627323],
        [ 0.04521583,  0.03147674, -0.00361334, -0.04899826,
          0.03517338, -0.00214362, -0.02061966,  0.04645291,
          0.03420972,  0.03603773],
        [-0.04139786, -0.02385365, -0.04399638, -0.0

In [73]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [74]:
embedded_docs[0]

array([   0,    0,    0, 3005, 7648, 3295, 3005, 6585], dtype=int32)

In [75]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[[-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.02259526,  0.01604018, -0.02330185,  0.00234685,
          0.02625885,  0.03046217, -0.02655741,  0.03261794,
          0.02299437, -0.01688639],
        [-0.04139786, -0.02385365, -0.04399638, -0.03862389,
          0.04960659, -0.04309141, -0.02511778, -0.02147905,
          0.04910827,  0.01750758],
        [-0.02780038,  0.02473172, -0.00084607,  0.00022495,
          0.02255764, -0.03845737,  0.01712784,  0.03489533,
         -0.03803753, -0.03627323],
        [ 0.04521583,  0.03147674, -0.00361334, -0.04899826,
          0.03517338, -0.00214362, -0.02061966,  0.04645291,
          0.03420972,  0.03603773],
        [-0.04139786, -0.02385365, -0.04399638, -0.0